fix: add new type and fix attribute name
aphp/Cohort360-FrontEnd pull request #926
Opened 2023-12-15 15:03 UTC by thicham43

## Fixes
replace `care_site_id` by `perimeter_id` to match the backend's response when calling `GET /accesses/accesses/my-data-rights/?perimeters_ids=xxxxx,yyyy,zzzz`

## Description
this bug causes the user to have `pseudonymized` access when exploring a perimeter even if he has `nominative` access

## Technical details
added new type `DataRights` to enhance type checking

## Tests
None

2023-12-15 18:28 UTC, pl-buiquang requested changes

2023-12-15 18:28 UTC, pl-buiquang commented on src/services/aphp/servicePerimeters.ts
> +    const rightsData = (rightResponse.data as DataRights[]) ?? []
It's better to type the api method (src/services/aphp/callApi.ts:983)
```
export const fetchPerimeterAccesses = async (perimeter: string): Promise<AxiosResponse<DataRights[]>> => {
  const response = await apiBackend.get<DataRights[]>(`accesses/accesses/my-data-rights/?perimeters_ids=${perimeter}`)
  return response
}
```

2023-12-15 18:28 UTC, pl-buiquang commented on src/services/aphp/servicePerimeters.ts
> +    const rightsData = (rightResponse.data as DataRights[]) ?? []
Every API method should be typed (but that's another PR/ticket..)

2023-12-15 18:29 UTC, pl-buiquang commented on src/services/aphp/servicePerimeters.ts
> +    const rightsData = (rightResponse.data as DataRights[]) ?? []
But thanks for the typing effort though :)

2023-12-18 09:02 UTC, thicham43 commented on src/services/aphp/servicePerimeters.ts
> +    const rightsData = (rightResponse.data as DataRights[]) ?? []
done

2023-12-18 09:29 UTC, Mehdi-BOUYAHIA approved these changes

2023-12-18 09:31 UTC, Mehdi-BOUYAHIA approved these changes

2023-12-18 09:32 UTC, merged