2471#new flow delete saved filters
aphp/Cohort360-FrontEnd pull request #948
Opened 2024-02-01 16:26 UTC by aetchego

Proposition de design + ui friendly

2024-02-13 09:16 UTC, pl-buiquang requested changes
Also fix the lint warnings and error (unused import, formatting, ...)

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/ui/List/ListItems.tsx
> +      id="scrollableDiv"
this is an shareable ui element, it should not have a static id

2024-02-13 09:16 UTC, pl-buiquang commented on src/mappers/pmsi.ts
> +  }
why two functions (one for pmsi and another for medication) instead of one ? `mapToLabel (type: ResourceType): string` and `mapToAttributeName(type: ResourceType): string`

2024-02-13 09:16 UTC, pl-buiquang commented on src/services/aphp/serviceMedication.ts
> +}
why duplicate the existing (in serviceCohortCreation) functions  ? if you just need to try-catch call, you could still create an utility function for this
```
const withDefaultValue = async <T>(apiCall: () => Promise<T>, defaultValue: T): Promise<T> => {
  try {
    const response = await apiCall()
    return response
  } catch (e) {
    return defaultValue
  }
}
```

2024-02-13 09:16 UTC, pl-buiquang commented on src/services/aphp/serviceMedication.ts
> +}
same thing for serviceImaging.ts, servicePmsi.ts and serviceBiology.ts
`serviceCohortCreation.ts` will probably need some small refactoring, but in the meantime, just centralize all methods here.

2024-02-13 09:16 UTC, pl-buiquang commented on src/types/valueSet.ts
> +}
why this ?
Where it's used, it doesn't correspond to the values used (eg. in `displaySystem` in `src/utils/displayValueSetSystem.ts` the values that are passed to the function are like `https://terminology.eds.aphp.fr/smt-medicament-ucd` and not in this enum)

2024-02-13 09:16 UTC, pl-buiquang commented on src/types/valueSet.ts
> +}
move that back to global `types.ts` file it doesn't need to have its own source file. it may also be refactored (in the future) to be reused more generically

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/DemographicForm/index.tsx
> +              active={birthdates[0] !== null || birthdates[1] !== null}
the semantics of this param changed (it means the opposite now) but not the value passed, is this really ok ?

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/DemographicForm/index.tsx
> +              active={birthdates[0] !== null || birthdates[1] !== null}
seeing the changes in `src/components/Filters/BirthdatesRangesFilters/index.tsx` i guess this is not ok

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/Filters/LoincFilter/index.tsx
> +const LoincFilter = ({ name, value, disabled = false, onFetch }: LoincFilterProps) => {
here onFetch is always equal to `fetchLoincCodes`. it's not needed to be passed as parameter.

Though, you could create a more generic component `AutoCompleteOptionsFilter` that will work for the cases of this filter and also, CodeFilter, AnabioFilter.

Same for other filters, there is always the same of reusable logic :
```
const context = useContext(FormContext)
const [value, setValue] = useState(defaultValue)

  useEffect(() => {
    if (context?.updateFormData) context.updateFormData(name, value)
  }, [value])
```

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/Filters/ModalityFilter/ModalityFilter.tsx
> +const ModalityFilter = ({ name, value, modalitiesList, disabled = false }: ModalityFilterProps) => {
Also, for this filters and other. Don't create component with the pattern `ComponentName/index.tsx` when they simple components.
also the `Filters` folder, not being a component  should be lower case. So we should have `filters/ModalityFilter.tsx`, `filters/OrderByFilter.tsx`, ...

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/Patient/PatientBiology/PatientBiology.tsx
> +      </Grid>
this code is duplicated in 8  files. create a component (like `FiltersToolbar` or something alike) to share the code.

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/Patient/PatientBiology/PatientBiology.tsx
> +          >
same here, this is duplicated code (except the submit method maybe)

2024-02-13 09:16 UTC, pl-buiquang commented on src/components/Patient/PatientBiology/PatientBiology.tsx
> +      </Modal>
And there also duplicated code

2024-02-13 09:16 UTC, pl-buiquang commented on src/mappers/filters.ts
> +}
this is nice.
we could extract that in a `types/fhir.ts` and reuse that in `callApi.ts`, since it would make easier to update when/if the fhir query params change. though it's not necessary to do it in this PR.

2024-02-20 13:51 UTC, aetchego commented on src/types/valueSet.ts
> +}
It is used to print " ATC: " or " UCD: " before the medication codes in the requeteur

2024-02-20 14:01 UTC, aetchego commented on src/components/Filters/LoincFilter/index.tsx
> +const LoincFilter = ({ name, value, disabled = false, onFetch }: LoincFilterProps) => {
keeping it like that because i plan a refacto of all that Filters Components to be more reusable and not tight with certain value sets

2024-02-20 14:08 UTC, aetchego commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/DemographicForm/index.tsx
> +              active={birthdates[0] !== null || birthdates[1] !== null}
bien vu merci

2024-02-20 14:35 UTC, aetchego commented on src/components/Patient/PatientBiology/PatientBiology.tsx
> +      </Grid>
comment ignored for this PR because refacto of Patient datas components needed !

2024-02-20 14:35 UTC, aetchego commented on src/components/Patient/PatientBiology/PatientBiology.tsx
> +          >
comment ignored for this PR because refacto of Patient datas components needed !

2024-02-20 14:35 UTC, aetchego commented on src/components/Patient/PatientBiology/PatientBiology.tsx
> +      </Modal>
comment ignored for this PR because refacto of Patient datas components needed !

2024-02-22 10:42 UTC, pl-buiquang approved these changes

2024-02-22 11:57 UTC, merged