feat: websocket count/create cohort to replace intervals calls - Ref …
aphp/Cohort360-FrontEnd pull request #976
Opened 2024-04-03 14:42 UTC by FlorentGouyon

…gestion-de-projet#2469

install: ajout de la dépendance react-use-websocket

feat: ajout de handshake avec envoi de token

feat: websocket samples, trial and errors

feat: impl° of websocket context

feat: websocket applied to reverse proxy nginx

fix: change local env url for websocket

feat: count cohort with websocket call

feat: websocket cohort status auto update - Ref gestion-de-projet#2469

chore: removed useless fragments

feat: fix cohort snapshot update in count cohort

feat: websocket listeners refactoring, eager loading change - Ref gestion-de-projet#2469

chore: operator simplification

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Technical details

## Tests

2024-04-09 08:41 UTC, ManelleG commented
Il manque l'ajout des websockets sur la page Mes requêtes :)
Du coup si un utilisateur crée une cohorte et qu'il va voir son statut dans la page Mes requêtes, son statut ne se met pas à jour

2024-04-23 15:06 UTC, FlorentGouyon commented
> Il manque l'ajout des websockets sur la page Mes requêtes :) Du coup si un utilisateur crée une cohorte et qu'il va voir son statut dans la page Mes requêtes, son statut ne se met pas à jour

C'est check et fix ;) ✅

2024-04-24 08:43 UTC, pl-buiquang requested changes

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/MedicationForm/index.tsx
> +import { EXPLORATION } from '../../../../../../../../constants'
why change this ?

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/GHM/index.tsx
> +import { EXPLORATION } from '../../../../../../../../constants'
why change this ?

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/Cim10Form/index.tsx
> +import { EXPLORATION } from '../../../../../../../../constants'
why change this ?

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/CCAM/index.tsx
> +import { EXPLORATION } from '../../../../../../../../constants'
why change this ?

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/BiologyForm/index.tsx
> +import { EXPLORATION } from '../../../../../../../../constants'
why change this ?

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/ControlPanel/ControlPanel.tsx
> +  const [socketLoading, setSocketLoading] = useState<LoadingStatus>(LoadingStatus.IDDLE)
countLoading would be more meaningful

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/ControlPanel/ControlPanel.tsx
> +  }, [webSocketContext?.websocket.lastMessage])
fix warning, update useEffect deps

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/CreationCohort/ControlPanel/ControlPanel.tsx
> +  }, [])
fix warning, update useEffect deps

2024-04-24 08:43 UTC, pl-buiquang commented on src/components/WebSocket/WebSocketProvider.tsx
> +  const websocket = useWebSocket<string>(`ws://${window.location.host}${BACK_API_URL}/ws/`, {
url won't work in production.
this should be the back url and in wss. 
just add additional env variable so that it would work in local env and prod env

2024-04-24 08:43 UTC, pl-buiquang commented on src/state/cohortCreation.ts
> +        await dispatch(
why await a dispatched action if the result isn't unwrapped and used ?

2024-04-24 08:43 UTC, pl-buiquang commented on src/state/cohortCreation.ts
> +        await dispatch(
why await a dispatched action if the result isn't unwrapped and used ?

2024-04-24 08:48 UTC, pl-buiquang commented on src/components/WebSocket/WebSocketProvider.tsx
> +  const websocket = useWebSocket<string>(`ws://${window.location.host}${BACK_API_URL}/ws/`, {
actually, the thing to do is to add the nginx reverse proxy configuration

2024-04-24 10:37 UTC, pl-buiquang commented on src/components/Requests/ProjectsTable/index.tsx
> +  }, [webSocketContext?.websocket.lastMessage])
here, the dependency should juste be webSocketconntext

2024-04-24 13:41 UTC, pl-buiquang approved these changes

2024-06-18 12:11 UTC, pl-buiquang approved these changes

2024-06-19 13:02 UTC, Mehdi-BOUYAHIA approved these changes

2024-06-19 13:03 UTC, merged