refactor: new scope tree
aphp/Cohort360-FrontEnd pull request #992
Opened 2024-05-21 09:13 UTC by aetchego

## Refacto ScopeTree

2024-07-08 07:17 UTC, pl-buiquang commented on src/utils/url.ts
> +export const getInclusionCriteriaUrl = (inclusionCriteria: any, index: any) => {
any

2024-07-09 09:07 UTC, pl-buiquang requested changes

2024-07-09 09:07 UTC, pl-buiquang commented on src/types/scope.ts
> +]
an array should not be a type (or it should be a disjonction of the different SourceValue)

2024-07-09 09:07 UTC, pl-buiquang commented on src/types/scope.ts
> +}
this enum have keys with same values. This should not be a type but a simple configuration json object.

2024-07-09 09:07 UTC, pl-buiquang commented on src/types/hierarchy.ts
> +export type Hierarchy<T, S> = T & {
set default `T=string` and `S={}` to avoid having to type simple hierarchies with everywhere in the current code

2024-07-09 09:07 UTC, pl-buiquang commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/MedicationForm/components/Form/MedicationForm.tsx
> +            ? criteriaData.data.prescriptionTypes.find((p: Hierarchy<any, any>) => p.id === prescriptionType.id)
replace every `Hierarchy<any, any>` with the correct types

2024-07-10 10:11 UTC, aetchego commented on src/components/CreationCohort/DiagramView/components/LogicalOperator/components/CriteriaRightPanel/MedicationForm/components/Form/MedicationForm.tsx
> +            ? criteriaData.data.prescriptionTypes.find((p: Hierarchy<any, any>) => p.id === prescriptionType.id)
à faire dans le ticket d'harmonisation textuelle

2024-07-10 10:35 UTC, aetchego commented on src/utils/url.ts
> +export const getInclusionCriteriaUrl = (inclusionCriteria: any, index: any) => {
alors ça a priori j'avais juste changé le fichier .js en .ts mais je vois que cette méthode n'est pas utilisée donc je la supprime

2024-07-10 14:46 UTC, aetchego commented on src/types/scope.ts
> +]
Code supprimé

2024-07-10 14:47 UTC, aetchego commented on src/types/hierarchy.ts
> +export type Hierarchy<T, S> = T & {
à faire dans le ticket d'harmonisation textuelle ou par Paul

2024-07-10 15:04 UTC, aetchego commented on src/types/scope.ts
> +}
Modifié

2024-07-11 08:09 UTC, pl-buiquang commented on src/types/scope.ts
> +}
c'est toujours pas ok. c'est encore un enum avec des éléments avec la meme valeur. 
genre `SourceType.BIOLOGY === SourceType.CIM10 => true ! ` pour un enum c'est étrange.
faudrait que ça soit juste une map : 
```
export const SOURCE_TYPES = {
   BIOLOGY: SourceValue.HOPITAL,
   ...
}

2024-07-11 09:09 UTC, aetchego commented on src/types/scope.ts
> +}
oui sorry j'ai écrit mon commentaire trop vite, je suis en train de faire des modifs

2024-07-11 12:46 UTC, pl-buiquang approved these changes

2024-07-19 09:23 UTC, Mehdi-BOUYAHIA approved these changes

2024-07-19 09:24 UTC, merged